### ISSUE TITLE
1.0 - things that should use / work with go-wof-spr

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-spr#1]
- [x] https://github.com/whosonfirst/go-whosonfirst-pip
- [x] https://github.com/whosonfirst/go-whosonfirst-tile38
- [ ] https://github.com/whosonfirst/go-whosonfirst-api
- [ ] https://github.com/whosonfirst/go-whosonfirst-iplookup (low-ish priority)
- [ ] https://github.com/whosonfirst/go-whosonfirst-breaches (low priority)
- [ ] https://github.com/whosonfirst/go-whosonfirst-nearby (low priority)

**Comment by straup** [comment]
No longer relevant.
